apiVersion: v1
entries:
  ncm-issuer:
  - apiVersion: v1
    appVersion: 1.1.9
    created: "2026-01-20T09:24:50.438498132Z"
    description: A Helm chart for cert-manager external issuer for integration with
      the Nokia NetGuard Certificate Manager (NCM) PKI system
    digest: 8f4c31586d0d1ee2f610d779ccc90f312d836f2e7d550d4cc8a90fe7cd61da1c
    home: https://github.com/nokia/ncm-issuer
    icon: https://i.imgur.com/G2p0BwS.png
    keywords:
    - ncm-issuer
    - cert-manager
    - com.nokia.ncm.certifier
    - tls
    kubeVersion: '>= 1.25.0-0 < 1.36.0-0'
    maintainers:
    - email: misiektoja-github@rm-rf.ninja
      name: Michal Szymanski
    name: ncm-issuer
    sources:
    - https://github.com/nokia/ncm-issuer
    urls:
    - ncm-issuer-1.1.9-chart.tgz
    version: 1.1.9-chart
  - apiVersion: v1
    appVersion: 1.1.8
    created: "2026-01-20T09:24:50.437993866Z"
    description: A Helm chart for cert-manager external issuer for integration with
      the Nokia NetGuard Certificate Manager (NCM) PKI system
    digest: db93f766bbb24f9f575d7de0df9de486321b6c8739e325b9c08200f3754ddef0
    home: https://github.com/nokia/ncm-issuer
    icon: https://i.imgur.com/G2p0BwS.png
    keywords:
    - ncm-issuer
    - cert-manager
    - com.nokia.ncm.certifier
    - tls
    kubeVersion: '>= 1.24.0-0 < 1.35.0-0'
    maintainers:
    - email: misiektoja-github@rm-rf.ninja
      name: Michal Szymanski
    name: ncm-issuer
    sources:
    - https://github.com/nokia/ncm-issuer
    urls:
    - ncm-issuer-1.1.8-chart.tgz
    version: 1.1.8-chart
  - apiVersion: v1
    appVersion: 1.1.7
    created: "2026-01-20T09:24:50.437520787Z"
    description: A Helm chart for cert-manager external issuer for integration with
      the Nokia NetGuard Certificate Manager (NCM) PKI system
    digest: e41365032c74c47898d8213843ec5ea83d99542939501b29086a06ec9f1dff05
    home: https://github.com/nokia/ncm-issuer
    icon: https://i.imgur.com/G2p0BwS.png
    keywords:
    - ncm-issuer
    - cert-manager
    - com.nokia.ncm.certifier
    - tls
    kubeVersion: '>= 1.24.0-0 < 1.34.0-0'
    maintainers:
    - email: misiektoja-github@rm-rf.ninja
      name: Michal Szymanski
    name: ncm-issuer
    sources:
    - https://github.com/nokia/ncm-issuer
    urls:
    - ncm-issuer-1.1.7-chart.tgz
    version: 1.1.7-chart
  - apiVersion: v1
    appVersion: 1.1.6
    created: "2026-01-20T09:24:50.436960136Z"
    description: A Helm chart for cert-manager external issuer for integration with
      the Nokia NetGuard Certificate Manager (NCM) PKI system
    digest: 22596552cdecadbe058cfb96143f8d6d396d57cf930ba934b546b38e3275f45c
    home: https://github.com/nokia/ncm-issuer
    icon: https://i.imgur.com/G2p0BwS.png
    keywords:
    - ncm-issuer
    - cert-manager
    - com.nokia.ncm.certifier
    - tls
    kubeVersion: '>= 1.24.0-0 < 1.34.0-0'
    maintainers:
    - email: misiektoja-github@rm-rf.ninja
      name: Michal Szymanski
    name: ncm-issuer
    sources:
    - https://github.com/nokia/ncm-issuer
    urls:
    - ncm-issuer-1.1.6.tgz
    version: 1.1.6
  - apiVersion: v1
    appVersion: 1.1.5
    created: "2026-01-20T09:24:50.436489562Z"
    description: A Helm chart for cert-manager external issuer for integration with
      the Nokia NetGuard Certificate Manager (NCM) PKI system
    digest: 3b53ca25b854960b5712717f0daa43ef17eb014f5d71f73f1a137c0318284eb7
    home: https://github.com/nokia/ncm-issuer
    icon: https://i.imgur.com/G2p0BwS.png
    keywords:
    - ncm-issuer
    - cert-manager
    - com.nokia.ncm.certifier
    - tls
    kubeVersion: '>= 1.24.0-0 < 1.34.0-0'
    maintainers:
    - email: misiektoja-github@rm-rf.ninja
      name: Michal Szymanski
    name: ncm-issuer
    sources:
    - https://github.com/nokia/ncm-issuer
    urls:
    - ncm-issuer-1.1.5.tgz
    version: 1.1.5
  - apiVersion: v1
    appVersion: 1.1.4
    created: "2026-01-20T09:24:50.435955891Z"
    description: A Helm chart for cert-manager external issuer for integration with
      the Nokia NetGuard Certificate Manager (NCM) PKI system
    digest: ba4b75be28c330f17cb6c727f5c138a6b60fb3ef45bc5e8ef336e1c59d7a684d
    home: https://github.com/nokia/ncm-issuer
    icon: https://i.imgur.com/G2p0BwS.png
    keywords:
    - ncm-issuer
    - cert-manager
    - com.nokia.ncm.certifier
    - tls
    kubeVersion: '>= 1.24.0-0 < 1.33.0-0'
    maintainers:
    - email: misiektoja-github@rm-rf.ninja
      name: Michal Szymanski
    name: ncm-issuer
    sources:
    - https://github.com/nokia/ncm-issuer
    urls:
    - ncm-issuer-1.1.4.tgz
    version: 1.1.4
  - apiVersion: v1
    appVersion: 1.1.3
    created: "2026-01-20T09:24:50.435466573Z"
    description: A Helm chart for cert-manager external issuer for integration with
      the Nokia NetGuard Certificate Manager (NCM) PKI system
    digest: c568ec2a12c92a3806d6dc905f98f763efbd068ffa99164fb2dfe3061d60bd98
    home: https://github.com/nokia/ncm-issuer
    icon: https://i.imgur.com/G2p0BwS.png
    keywords:
    - ncm-issuer
    - cert-manager
    - com.nokia.ncm.certifier
    - tls
    kubeVersion: '>= 1.24.0-0 < 1.33.0-0'
    maintainers:
    - email: misiektoja-github@rm-rf.ninja
      name: Michal Szymanski
    name: ncm-issuer
    sources:
    - https://github.com/nokia/ncm-issuer
    urls:
    - ncm-issuer-1.1.3.tgz
    version: 1.1.3
  - apiVersion: v1
    appVersion: 1.1.2
    created: "2026-01-20T09:24:50.434910811Z"
    description: A Helm chart for cert-manager external issuer with NCM (NetGuard
      Certificate Manager)
    digest: 911fac3daa011958b88443571f759f2af2a37ff9990466beccbc6f89b9c4381a
    home: https://github.com/nokia/ncm-issuer
    icon: https://i.imgur.com/G2p0BwS.png
    keywords:
    - ncm-issuer
    - cert-manager
    - com.nokia.ncm.certifier
    - tls
    kubeVersion: '>= 1.24.0-0 < 1.30.0-0'
    maintainers:
    - email: misiektoja-github@rm-rf.ninja
      name: Michal Szymanski
    name: ncm-issuer
    sources:
    - https://github.com/nokia/ncm-issuer
    urls:
    - ncm-issuer-1.1.2.tgz
    version: 1.1.2
  - apiVersion: v1
    appVersion: 1.1.1
    created: "2026-01-20T09:24:50.433231237Z"
    description: A Helm chart for cert-manager external issuer with NCM (NetGuard
      Certificate Manager)
    digest: 51775eca38ca2d9dffc9e4072641c23a4e2b34b863d16262255886b6048d9f57
    home: https://github.com/nokia/ncm-issuer
    icon: https://i.imgur.com/G2p0BwS.png
    keywords:
    - ncm-issuer
    - cert-manager
    - com.nokia.ncm.certifier
    - tls
    kubeVersion: '>= 1.24.0-0 < 1.30.0-0'
    maintainers:
    - email: sara.ryfczynska@nokia.com
      name: Sara Ryfczynska
    - email: dawid.machoczek@nokia.com
      name: Dawid Machoczek
    - email: adam.korba@nokia.com
      name: Adam Korba
    name: ncm-issuer
    sources:
    - https://github.com/nokia/ncm-issuer
    urls:
    - ncm-issuer-1.1.1.tgz
    version: 1.1.1
  - apiVersion: v1
    appVersion: 1.1.0
    created: "2026-01-20T09:24:50.432713827Z"
    description: A Helm chart for cert-manager external issuer with NCM (NetGuard
      Certificate Manager)
    digest: d18f42a44a3614a60a315821fce62b76cadada9e0af1d58a6bc2522d4888e877
    home: https://github.com/nokia/ncm-issuer
    icon: https://i.imgur.com/G2p0BwS.png
    keywords:
    - ncm-issuer
    - cert-manager
    - com.nokia.ncm.certifier
    - tls
    kubeVersion: '>= 1.18.0-0 < 1.28.0-0'
    maintainers:
    - email: sara.ryfczynska@nokia.com
      name: Sara Ryfczynska
    - email: dawid.machoczek@nokia.com
      name: Dawid Machoczek
    - email: adam.korba@nokia.com
      name: Adam Korba
    name: ncm-issuer
    sources:
    - https://github.com/nokia/ncm-issuer
    urls:
    - ncm-issuer-1.1.0.tgz
    version: 1.1.0
generated: "2026-01-20T09:24:50.431723718Z"
