apiVersion: v1
name: ncm-issuer
appVersion: 1.1.0
version: 1.1.0
kubeVersion: 1.18 - 1.27
description: A Helm chart for cert-manager external issuer with NCM (NetGuard Certificate Manager)
home: https://github.com/nokia/ncm-issuer
sources:
  - https://github.com/nokia/ncm-issuer
icon: https://i.imgur.com/G2p0BwS.png
keywords:
  - ncm-issuer
  - cert-manager
  - com.nokia.ncm.certifier
  - tls
maintainers:
- email: sara.ryfczynska@nokia.com
  name: Sara Ryfczynska
- email: dawid.machoczek@nokia.com
  name: Dawid Machoczek
- email: adam.korba@nokia.com
  name: Adam Korba