apiVersion: v1
name: ncm-issuer
appVersion: 1.1.9
version: 1.1.9-chart
kubeVersion: ">= 1.25.0-0 < 1.36.0-0"
description: A Helm chart for cert-manager external issuer for integration with the Nokia NetGuard Certificate Manager (NCM) PKI system
home: https://github.com/nokia/ncm-issuer
sources:
  - https://github.com/nokia/ncm-issuer
icon: https://i.imgur.com/G2p0BwS.png
keywords:
  - ncm-issuer
  - cert-manager
  - com.nokia.ncm.certifier
  - tls
maintainers:
- name: Michal Szymanski
  email: misiektoja-github@rm-rf.ninja
