name: enrollment tests

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 * * 6'

jobs:
  issuer_test:
    name: "ncm-issuer test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8sversion: ['1.21', '1.22', '1.23', '1.24', '1.25', '1.26']
        certmgrversion: ['1.5.5', '1.6.2', '1.8.2', '1.9.2', '1.11.0']
    steps:

    - name: "checkout GIT"
      uses: actions/checkout@v2
    - uses: actions/setup-go@v3
    - run: go version

    - name: "build plugin"
      run: |
        go mod vendor
        make docker_build_img
        make save

    - name: "install microk8s"
      run: |
        sudo snap install microk8s --classic --channel=${{ matrix.k8sversion }}/stable
        sudo microk8s status --wait-ready
        sudo microk8s enable helm3
        sudo microk8s enable dns
        echo K8S_VERSION=$(sudo microk8s.kubectl version --short=true|grep -Po 'Server Version: \K.*' -m 1) >> $GITHUB_ENV
    - run: echo "k8s ${{ env.K8S_VERSION }}"
    
    - name: "install cert-manager charts"
      run: |
        sudo microk8s.kubectl create namespace cert-manager
        sudo microk8s.helm3 repo add jetstack https://charts.jetstack.io
        sudo microk8s.helm3 repo update
        sudo microk8s.helm3 install cert-manager jetstack/cert-manager --namespace cert-manager --version v${{ matrix.certmgrversion }} --set installCRDs=true
        echo CERTMGR_VERSION=$(sudo microk8s.helm3 list -n cert-manager -o yaml|grep -Po 'cert-manager-\K.*' -m 1) >> $GITHUB_ENV
    - run: echo "cert-manager ${{ env.CERTMGR_VERSION }}"

    - name: "sleep for 10s"
      uses: juliangruber/sleep-action@v1
      with:
        time: 10s

    - name: "cert-manager status"
      run: |
        sudo microk8s.helm3 list -A
        sudo microk8s.kubectl get pods -A
        sudo microk8s.kubectl -n cert-manager logs `sudo microk8s.kubectl get pods -n cert-manager -l app=cert-manager -o jsonpath='{.items[0].metadata.name}'`|tail -25
        
    - name: "install kubectl cert-manager plugin"
      run: |
          OS=$(go env GOOS); ARCH=$(go env GOARCH); curl -sSL -o kubectl-cert-manager.tar.gz "https://github.com/cert-manager/cert-manager/releases/download/v${{ matrix.certmgrversion }}/kubectl-cert_manager-$OS-$ARCH.tar.gz"
          tar xzf kubectl-cert-manager.tar.gz
          sudo mv kubectl-cert_manager /usr/local/bin

    - name: "prepare environment / create namespace and secrets"
      run: |
        mkdir -p data/logs
        echo "$NCM_CA_BUNDLE" > data/ca_bundle.pem
        cp .github/*.yml data/
        sed -i "s|ncmSERVER: NCM_SRV|ncmSERVER: $NCM_HOST|g" data/ncm-issuer.yml
        sudo microk8s.kubectl create namespace ncm-issuer
        sudo microk8s.kubectl create secret generic ncm-issuer -n ncm-issuer --from-literal=username=$NCM_USER --from-literal=usrPassword=$NCM_PASSWORD
        sudo microk8s.kubectl create secret generic ncm-issuer-bundle -n ncm-issuer --from-file=cacert=data/ca_bundle.pem
      env:
        NCM_HOST: ${{ secrets.NCM_HOST }}
        NCM_USER: ${{ secrets.NCM_USER }}
        NCM_PASSWORD: ${{ secrets.NCM_PASSWORD }}
        NCM_CA_BUNDLE: ${{ secrets.NCM_CA_BUNDLE }}

    - name: "install ncm-issuer plugin"
      run: |
        sudo microk8s.helm3 install -n ncm-issuer ncm-issuer "$(pwd)/helm"
        
    - name: "sleep for 10s"
      uses: juliangruber/sleep-action@v1
      with:
        time: 10s

    - name: "ncm-issuer plugin status"
      run: |
        sudo microk8s.helm3 list -A
        sudo microk8s.kubectl get pods -A
        sudo microk8s.kubectl -n ncm-issuer logs `sudo microk8s.kubectl get pods -A -l app=ncm-issuer -o jsonpath='{.items[0].metadata.name}'`|tail -25
       
    - name: "create issuer"
      run: |
        sudo microk8s.kubectl apply -f data/ncm-issuer.yml
        sudo microk8s.kubectl get issuers.certmanager.ncm.nokia.com -n ncm-issuer
    - name: "sleep for 15s"
      uses: juliangruber/sleep-action@v1
      with:
        time: 15s

    - name: "check issuer status"
      run: |
        sudo microk8s.kubectl get issuers.certmanager.ncm.nokia.com -n ncm-issuer
        sudo microk8s.kubectl -n ncm-issuer describe issuers.certmanager.ncm.nokia.com ncm
        sudo microk8s.kubectl get issuers.certmanager.ncm.nokia.com -n ncm-issuer | grep -i True
    - name: "create certificate resource"
      run: |
        sudo microk8s.kubectl apply -f data/cert-resource.yml

    - name: "sleep for 15s"
      uses: juliangruber/sleep-action@v1
      with:
        time: 15s

    - name: "check certificate resource"
      run: |
        sudo microk8s.kubectl cert-manager status certificate ncm-cert -n ncm-issuer
        sudo microk8s.kubectl describe cert ncm-cert -n ncm-issuer
        sudo microk8s.kubectl describe cert ncm-cert -n ncm-issuer  | grep "The certificate has been successfully issued"
        sudo microk8s.kubectl describe certificaterequest ncm-cert -n ncm-issuer
        sudo microk8s.kubectl describe certificaterequest ncm-cert -n ncm-issuer | grep "Approved"
        sudo microk8s.kubectl describe certificaterequest ncm-cert -n ncm-issuer | grep "Issued"
        sudo microk8s.kubectl describe certificaterequest ncm-cert -n ncm-issuer | grep "Certificate:" | awk '{print $2}' | base64 -d > /tmp/cert.der
        sudo microk8s.kubectl describe certificaterequest ncm-cert -n ncm-issuer | grep "Ca:" | awk '{print $2}' | base64 -d > /tmp/ca.pem
        openssl x509 -in /tmp/cert.der -text -noout
        openssl verify -CAfile /tmp/ca.pem --untrusted /tmp/cert.der /tmp/cert.der

    - name: "renew certificate"
      run: |
        sudo microk8s.kubectl cert-manager renew ncm-cert -n ncm-issuer

    - name: "sleep for 10s"
      uses: juliangruber/sleep-action@v1
      with:
        time: 10s

    - name: "check certificate resource"
      run: |
        sudo microk8s.kubectl get certificaterequest -n ncm-issuer
        sudo microk8s.kubectl cert-manager status certificate ncm-cert -n ncm-issuer
        sudo microk8s.kubectl cert-manager status certificate ncm-cert -n ncm-issuer | grep "No CertificateRequest found for this Certificate"
        sudo microk8s.kubectl describe certificaterequest ncm-cert -n ncm-issuer | grep "Certificate:" | awk '{print $2}' | base64 -d > /tmp/cert.der
        openssl x509 -in /tmp/cert.der -text -noout

    - name: "[ * ] collecting test logs"
      continue-on-error: true
      if: ${{ failure() }}
      run: |
        sudo  microk8s.kubectl get namespaces > data/logs/get_namespaces.log
        sudo microk8s.kubectl get po -A > data/logs/get_pods.log
        sudo microk8s.kubectl describe pods ncm-issuer -n ncm-issuer > data/logs/describe_ncm-issuer.log
        sudo microk8s.kubectl get secrets -n ncm-issuer > data/logs/get_secrets.log
        sudo microk8s.kubectl get issuers.certmanager.ncm.nokia.com -n ncm-issuer > data/logs/get_issuers.log
        sudo microk8s.kubectl describe issuer.certmanager.ncm.nokia.com  -n ncm-issuer > data/logs/describe_issuer.log
        sudo microk8s.kubectl -n ncm-issuer logs  `sudo microk8s.kubectl get pods -A -l app=ncm-issuer -o jsonpath='{.items[0].metadata.name}'` > data/logs/ncm-issuer.log
        sudo microk8s.kubectl -n cert-manager logs `sudo microk8s.kubectl get pods -n cert-manager -l app=cert-manager -o jsonpath='{.items[0].metadata.name}'` > data/logs/cert-manager.log
        sudo microk8s.kubectl get certificaterequest -n ncm-issuer > data/logs/get_csr.log
        sudo  microk8s.kubectl describe certificaterequest ncm-cert -n ncm-issuer > data/logs/describe_csr.log
        sudo microk8s.kubectl get certificate -n ncm-issuer > data/logs/get_certificate.log
        sudo microk8s.kubectl describe certificate ncm-cert -n ncm-issuer > data/logs/describe_certificate.log
        mkdir -p ${{ github.workspace }}/artifact/upload
        sudo cp -rp data/ ${{ github.workspace }}/artifact/data/
        sudo tar -C ${{ github.workspace }}/artifact/ -cvzf ${{ github.workspace }}/artifact/upload/artifact.tar.gz data
    - name: "[ * ] uploading artificates"
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: logs-k${{ matrix.k8sversion }}-${{ matrix.certmgrversion }}.tar.gz
        path: ${{ github.workspace }}/artifact/upload/

  clusterissuer_test:
    name: "ncm-clusterissuer test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8sversion: ['1.21', '1.22', '1.23', '1.24', '1.25', '1.26']
        certmgrversion: ['1.5.5', '1.6.2', '1.8.2', '1.9.2', '1.11.0']
    steps:

    - name: "checkout GIT"
      uses: actions/checkout@v2
    - uses: actions/setup-go@v3
    - run: go version

    - name: "build plugin"
      run: |
        go mod vendor
        make docker_build_img
        make save

    - name: "install microk8s"
      run: |
        sudo snap install microk8s --classic --channel=${{ matrix.k8sversion }}/stable
        sudo microk8s status --wait-ready
        sudo microk8s enable helm3
        sudo microk8s enable dns
        echo K8S_VERSION=$(sudo microk8s.kubectl version --short=true|grep -Po 'Server Version: \K.*' -m 1) >> $GITHUB_ENV
    - run: echo "k8s ${{ env.K8S_VERSION }}"

    - name: "install cert-manager charts"
      run: |
        sudo microk8s.kubectl create namespace cert-manager
        sudo microk8s.helm3 repo add jetstack https://charts.jetstack.io
        sudo microk8s.helm3 repo update
        sudo microk8s.helm3 install cert-manager jetstack/cert-manager --namespace cert-manager --version v${{ matrix.certmgrversion }} --set installCRDs=true
        echo CERTMGR_VERSION=$(sudo microk8s.helm3 list -n cert-manager -o yaml|grep -Po 'cert-manager-\K.*' -m 1) >> $GITHUB_ENV
    - run: echo "cert-manager ${{ env.CERTMGR_VERSION }}"

    - name: "sleep for 10s"
      uses: juliangruber/sleep-action@v1
      with:
        time: 10s

    - name: "cert-manager status"
      run: |
        sudo microk8s.helm3 list -A        
        sudo microk8s.kubectl get pods -A
        sudo microk8s.kubectl -n cert-manager logs `sudo microk8s.kubectl get pods -n cert-manager -l app=cert-manager -o jsonpath='{.items[0].metadata.name}'`|tail -25
   
    - name: "install kubectl cert-manager plugin"
      run: |
          OS=$(go env GOOS); ARCH=$(go env GOARCH); curl -sSL -o kubectl-cert-manager.tar.gz "https://github.com/cert-manager/cert-manager/releases/download/v${{ matrix.certmgrversion }}/kubectl-cert_manager-$OS-$ARCH.tar.gz"
          tar xzf kubectl-cert-manager.tar.gz
          sudo mv kubectl-cert_manager /usr/local/bin

    - name: "prepare environment / create namespace and secrets"
      run: |
        mkdir -p data/logs
        echo "$NCM_CA_BUNDLE" > data/ca_bundle.pem
        cp .github/*.yml data/
        sed -i "s|ncmSERVER: NCM_SRV|ncmSERVER: $NCM_HOST|g" data/ncm-issuer.yml
        sed -i "s|kind: Issuer|kind: ClusterIssuer|g" data/ncm-issuer.yml
        sed -i "s|secretName: ncm-issuer|authNameSpace: ncm-issuer-auth\n   secretName: ncm-issuer|g" data/ncm-issuer.yml
        sed -i "s|namespace: ncm-issuer|namespace: ncm-cert|g" data/cert-resource.yml
        sed -i "s|kind: Issuer|kind: ClusterIssuer|g" data/cert-resource.yml
        sudo microk8s.kubectl create namespace ncm-cert
        sudo microk8s.kubectl create namespace ncm-issuer
        sudo microk8s.kubectl create namespace ncm-issuer-auth
        sudo microk8s.kubectl create secret generic ncm-issuer -n ncm-issuer-auth --from-literal=username=$NCM_USER --from-literal=usrPassword=$NCM_PASSWORD
        sudo microk8s.kubectl create secret generic ncm-issuer-bundle -n ncm-issuer-auth --from-file=cacert=data/ca_bundle.pem
      env:
        NCM_HOST: ${{ secrets.NCM_HOST }}
        NCM_USER: ${{ secrets.NCM_USER }}
        NCM_PASSWORD: ${{ secrets.NCM_PASSWORD }}
        NCM_CA_BUNDLE: ${{ secrets.NCM_CA_BUNDLE }}

    - name: "install ncm-issuer plugin"
      run: |
        sudo microk8s.helm3 install -n ncm-issuer ncm-issuer "$(pwd)/helm"
        
    - name: "sleep for 10s"
      uses: juliangruber/sleep-action@v1
      with:
        time: 10s

    - name: "ncm-issuer plugin status"
      run: |
        sudo microk8s.helm3 list -A
        sudo microk8s.kubectl get pods -A
        sudo microk8s.kubectl -n ncm-issuer logs `sudo microk8s.kubectl get pods -A -l app=ncm-issuer -o jsonpath='{.items[0].metadata.name}'`|tail -25
   
    - name: "create issuer"
      run: |
        sudo microk8s.kubectl apply -f data/ncm-issuer.yml
        sudo microk8s.kubectl get clusterissuers.certmanager.ncm.nokia.com -n ncm-issuer

    - name: "sleep for 15s"
      uses: juliangruber/sleep-action@v1
      with:
        time: 15s

    - name: "check issuer status"
      run: |
        sudo microk8s.kubectl get clusterissuers.certmanager.ncm.nokia.com -n ncm-issuer
        sudo microk8s.kubectl -n ncm-issuer describe clusterissuers.certmanager.ncm.nokia.com ncm
        sudo microk8s.kubectl get clusterissuers.certmanager.ncm.nokia.com -n ncm-issuer | grep -i True

    - name: "create certificate resource"
      run: |
        cat data/cert-resource.yml
        sudo microk8s.kubectl apply -f data/cert-resource.yml

    - name: "sleep for 15s"
      uses: juliangruber/sleep-action@v1
      with:
        time: 15s

    - name: "check certificate resource"
      run: |
        sudo microk8s.kubectl cert-manager status certificate ncm-cert -n ncm-cert
        sudo microk8s.kubectl describe cert ncm-cert -n ncm-cert
        sudo microk8s.kubectl describe cert ncm-cert -n ncm-cert  | grep "The certificate has been successfully issued"
        sudo microk8s.kubectl describe certificaterequest ncm-cert -n ncm-cert
        sudo microk8s.kubectl describe certificaterequest ncm-cert -n ncm-cert | grep "Approved"
        sudo microk8s.kubectl describe certificaterequest ncm-cert -n ncm-cert | grep "Issued"
        sudo microk8s.kubectl describe certificaterequest ncm-cert -n ncm-cert | grep "Certificate:" | awk '{print $2}' | base64 -d > /tmp/cert.der
        sudo microk8s.kubectl describe certificaterequest ncm-cert -n ncm-cert | grep "Ca:" | awk '{print $2}' | base64 -d > /tmp/ca.pem
        openssl x509 -in /tmp/cert.der -text -noout
        openssl verify -CAfile /tmp/ca.pem --untrusted /tmp/cert.der /tmp/cert.der

    - name: "renew certificate"
      run: |
        sudo microk8s.kubectl cert-manager renew ncm-cert -n ncm-cert

    - name: "sleep for 10s"
      uses: juliangruber/sleep-action@v1
      with:
        time: 10s

    - name: "check certificate resource"
      run: |
        sudo microk8s.kubectl get certificaterequest -n ncm-cert
        sudo microk8s.kubectl cert-manager status certificate ncm-cert -n ncm-cert
        sudo microk8s.kubectl cert-manager status certificate ncm-cert -n ncm-cert | grep "No CertificateRequest found for this Certificate"
        sudo microk8s.kubectl describe certificaterequest ncm-cert -n ncm-issuer | grep "Certificate:" | awk '{print $2}' | base64 -d > /tmp/cert.der
        openssl x509 -in /tmp/cert.der -text -noout       

    - name: "[ * ] collecting test logs"
      continue-on-error: true
      if: ${{ failure() }}
      run: |
        sudo  microk8s.kubectl get namespaces > data/logs/get_namespaces.log
        sudo microk8s.kubectl get po -A > data/logs/get_pods.log
        sudo microk8s.kubectl describe pods ncm-issuer -n ncm-issuer > data/logs/describe_ncm-issuer.log
        sudo microk8s.kubectl get secrets -n ncm-issuer > data/logs/get_secrets_ncm-issuer.log
        sudo microk8s.kubectl get secrets -n ncm-issuer-auth > data/logs/get_secrets_ncm-issuer-auth.log
        sudo microk8s.kubectl get secrets -n ncm-cert > data/logs/get_secrets_ncm-issuer-cert.log
        sudo microk8s.kubectl get clusterissuers.certmanager.ncm.nokia.com -n ncm-issuer > data/logs/get_issuers.log
        sudo microk8s.kubectl describe clusterissuer.certmanager.ncm.nokia.com  -n ncm-issuer > data/logs/describe_issuer.log
        sudo microk8s.kubectl -n ncm-issuer logs `sudo microk8s.kubectl get pods -A -l app=ncm-issuer -o jsonpath='{.items[0].metadata.name}'` > data/logs/ncm-issuer.log
        sudo microk8s.kubectl -n cert-manager logs `sudo microk8s.kubectl get pods -n cert-manager -l app=cert-manager -o jsonpath='{.items[0].metadata.name}'` > data/logs/cert-manager.log
        sudo microk8s.kubectl get certificaterequest -n ncm-cert > data/logs/get_csr.log
        sudo  microk8s.kubectl describe certificaterequest ncm-cert -n ncm-cert > data/logs/describe_csr.log
        sudo microk8s.kubectl get certificate -n ncm-cert > data/logs/get_certificate.log
        sudo microk8s.kubectl describe certificate ncm-cert -n ncm-cert > data/logs/describe_certificate.log
        mkdir -p ${{ github.workspace }}/artifact/upload
        sudo cp -rp data/ ${{ github.workspace }}/artifact/data/
        sudo tar -C ${{ github.workspace }}/artifact/ -cvzf ${{ github.workspace }}/artifact/upload/artifact.tar.gz data

    - name: "[ * ] uploading artifacts"
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: logs-k${{ matrix.k8sversion }}-${{ matrix.certmgrversion }}.tar.gz
        path: ${{ github.workspace }}/artifact/upload/
